# Generated by Django 3.0.3 on 2020-02-11 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year_released', models.IntegerField()),
                ('plot_description', models.TextField()),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='better_IMDB.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Movie_Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('country_of_birth', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie_Person_Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_person_role', to='better_IMDB.Movie')),
                ('movie_person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_person_role', to='better_IMDB.Movie_Person')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_person_role', to='better_IMDB.Role')),
            ],
        ),
    ]
