# Generated by Django 3.0.3 on 2020-02-11 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('better_IMDB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='director', to='better_IMDB.Movie_Person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='directors',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='better_IMDB.Movie_Person'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Movie_Person_Role',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
