# Generated by Django 3.0.3 on 2020-02-11 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('better_IMDB', '0004_auto_20200211_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='movies',
        ),
        migrations.RemoveField(
            model_name='director',
            name='movies',
        ),
        migrations.AddField(
            model_name='movie',
            name='directors',
            field=models.ManyToManyField(related_name='movies', to='better_IMDB.Director'),
        ),
    ]
