# Generated by Django 3.0.3 on 2020-02-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('better_IMDB', '0005_auto_20200211_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='movies', to='better_IMDB.Actor'),
        ),
    ]
