# Generated by Django 3.0.3 on 2020-02-11 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('better_IMDB', '0007_auto_20200211_2226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='genre',
            new_name='genres',
        ),
    ]
